### ISSUE TITLE
[Question] Would you consider making something else?

### ISSUE THREAD

**Issue by Darkmega18** [Miloet/TheManyModsOfLethalCompany#1]
Was this a one off item for the funnies, or would you consider expanding the amount of items or mechanics in the mod? As I had recently just made an idea based around a lightweight survival mechanic and found/bought food items which replenish it but also give other benefits while still on the moon.
Would that be something you'd be interested in expanding into?

**Comment by Miloet** [comment]
This was mainly just a one-off item but I have had ideas for other food items; Such as coffee that you get from a coffee brewer that is bought like the teleporter and then you fill up a piece of scrap such as the coffee mug or flask with coffee and drink for a speed- and stamina boost. 
I am also working on another mod that is a box of snacks that you give to the hoarding bugs to make them calm and non-aggressive (allowing you to steal from them)
Idk about adding further mechanics such as hunger as I feel like that goes against LC's core. If you have any ideas id be happy to hear them.

**Comment by Darkmega18** [comment]
Well it was a soft hunger mechanic. I'll copy the suggestion I had on the discord:

The player has a saturation number or meter which starts full. it displays when in the ship (or maybe in the escape menu?) but is hidden when outside.
Every time you go down to a map your saturation goes down by an amount. If you die, your saturation also goes down by a similar amount (acts as a reversible death penalty as such)

Using certain types of unique scraps (foods) or purchased equipments with varying costs on potency (consumeables) will replenish saturation and also bestow effects. Some may act like upgrades, bestowing minor permanent increases along with the temporary buffs until the next reset.

Idea of permanent increases comes from a game called dungeon maker, where the player upgrades stats by eating meals after each day passes. While temporary buffs are akin to just buff effects/stylized potions that last the mission after a good meal.

You can only use food items when saturation is below full. Having saturation during a map improves stamina regen and provides very slow health regen up to a configurable threshold.
If saturation dips to 0 or under you are instead slowed and have reduced stamina regen for each negative point. should likely be a maximum negative value and an optional "if you hit this negative value instantly die, but come back with 0 saturation next time".

Scrap food could include labeled and unlabeled food cans, your food item ideas or drinks salvaged from bottle crates perhaps. 

Something fun could be lunch boxes that act like presents but for food items. when you use them you break them open and it reveals someones lunch. like a subway sandwich or heavy's sandwich, or some other fun food items that look similar to those from familiar games. of course there'd be different potencies of foods too or some soft pity mechanics too, like stronger foods restore more saturation in one go, or eating food when in negative saturation would just set you back to 1 saturation straight away, that sort of thing.
while a fun storage object in the ship could be a fridge for storing food.

**Comment by Miloet** [comment]
I would say that having a general saturation with positive and especially negative effects that would either take away scrap from quota or act as a resource sink to keep up would work against LC's game design. I believe a Monster Hunter-esque approach could work better. You pick food based on the planet and the scenarios you might encounter. You're going to Titan and it's stormy? Eat some lighting-resistant food and you won't get one shot by random lighting. The planet is eclipsed? Eat some food to make you fast so you can run from giants and dogs. 

Having a general system with negative or positive consequences for eating or not eating I believe could be punishing and force the players to divert resources into and force them to engage with the mod or be punished for it. 

I do love the lunch box idea tho-

I believe that a mod like this would need some forethought into the game design and its wider effects. The execution with coding and such should be relatively simple however.

**Comment by Darkmega18** [comment]
being an enjoyer of a more scrub friendly game (I do a fair bit of rebalancing, cause of my skill issues...) of course I wouldn't suggest anything I don't think would be useable with enough thought. 
cause having high saturation for regen and stamina regen would be plenty of reason to have high saturation and engage with the mod for myself cause I often always bring a shovel for my own "comfort", cause I feel vulnerable without one (and I use lethal parry. :V) so regenning health and having that faster and quicker sprint to do more stuff in the short time allowed would be great.
Even if the hunger mechanic is mostly "all carrot and no stick" where saturation is only a benefit of eating food but without eating food and having no saturation it doesn't go away. Sorta like a decaying benefit for eating rather than a hard as nails survival mechanic.

I do usually say that configurability is king. So people can choose to allow it to go negative or not in their packs and configure the costs how they want with mods like advanced company.

The inclusion of lunch boxes, maybe a buyable ship object that can produce free "sustenance blocks" every map. (like these ones that are decorative objects from warframe universe)
https://static.wikia.nocookie.net/warframe/images/5/5a/SolarisFoodBoxDecoration.png/revision/latest?cb=20200917045944
https://static.wikia.nocookie.net/warframe/images/5/52/ZarimanNutritionCubeVitamins.png/revision/latest?cb=20220502051415
https://static.wikia.nocookie.net/warframe/images/6/67/ZarimanNutritionCubeCarbohydrate.png/revision/latest?cb=20220502051418
https://static.wikia.nocookie.net/warframe/images/b/b5/ZarimanNutritionBrickProtein.png/revision/latest?cb=20220502051419
https://static.wikia.nocookie.net/warframe/images/8/84/ZarimanNutritionCubeFat.png/revision/latest?cb=20220502051416
https://static.wikia.nocookie.net/warframe/images/9/9a/ZarimanNutritionCubeFiber.png/revision/latest?cb=20220502051417

it seems like some mods know how to guarantee or inject the generation of their own items into the worlds, like the shopping trolley object in late game upgrades mod which is set to only spawn on maps 20% of the time by default. You could maybe gaurantee some food spawns with the mod using that kind of technology. While cheap foods that only do saturation could be like 20-30 credits or such.

The same sustenance block producer could take like, beehives or even monster corpses from the sell bodies mod to produce special food cubes out of them.
Food being food it'd be primarily kept for keeping the crew going, but could be sold in the event that you're doing well.
Or concessions like food having a number of "bites/uses" to it that could be shared amongst the crew could also be good.

Funny vending machines placed on maps or even at the company that if you pay scrap to it like the gambling chip machine in the lethal casino mod it could dispense funny different colored drinks or chip packets to snack on, or you can try to steal from it with a shovel and it might dispense a few things but if you hit it too much it turns into some kind of robot or monster and tries to kill your asses. xD

---

Well, as much of a loss as it is that Advanced company has died along with it's leveling system that does open up an opportunity for a new leveling/upgrading/buff system providing mod to fill that void... ;)

**Comment by Darkmega18** [comment]
Well, as much of a loss as it is that Advanced company has died along with it's leveling system that does open up an opportunity for a new leveling/upgrading/buff system providing mod to fill that void... ;)
