### ISSUE TITLE
[NoNailsRequired] Paintings disappear on save & load [Conflict with GeneralImprovements/SmartItemSaving?]

### ISSUE THREAD

**Issue by donedonedone278** [Miloet/TheManyModsOfLethalCompany#10]
NoNailsRequired was an instant download for me, but just as a heads up to others it doesn't work quite right with my mods. I booted a ship that already had paintings, went to the company, hung up the paintings, went back into orbit, then saved and reloaded. The paintings disappeared. If this is a result of mod conflicts, it's probably SmartItemSaving or GeneralImprovements.

**Comment by Miloet** [comment]
Thank you for the info, i'll have a look!

**Comment by Miloet** [comment]
I found the issue and have pushed out an update now. It was a problem with the mod itself, not with any other mods.
