### ISSUE TITLE
[MISSING DEPENDANCY] Cruiser Tunes does not work without StaticNetcodeLib

### ISSUE THREAD

**Issue by ScandalTheVandal** [Miloet/TheManyModsOfLethalCompany#11]
Title says it all, was trying to figure it out for a while why Cruiser Tunes wasn't working when it was working before on my old profile, and after some testing I found that Cruiser Tunes requires StaticNetcodeLib, which is not at all stated on the mods Thunderstore page.

Just a heads up.

Thanks!

**Comment by Miloet** [comment]
I have no memory of using StaticNetcodeLib while making the mod...
I will look into it however!

**Comment by ScandalTheVandal** [comment]
> I have no memory of using StaticNetcodeLib while making the mod... I will look into it however!

All good, I was just very confused when I was trying to figure it out, I had my suspicions on a potentially missing dependency but couldn't be sure, so I did some thorough testing on a basically blank profile with no other mods and I was right, so I thought I'd just let you know :)

**Comment by Miloet** [comment]
After some testing I can confirm that it doesnt work without it on new profiles... I have 0 clue why or how. Thank you for bringing this to my attention.

**Comment by ScandalTheVandal** [comment]
> After some testing I can confirm that it doesnt work without it on new profiles... I have 0 clue why or how. Thank you for bringing this to my attention.

I only suspected it after I looked at the closed issues, one of them referring to how previously Cruiser Tunes required a NetworkPatcher mod, well, something like that, whether that has anything to do with it I'm not sure haha

Hope you're able to figure it out! :)

**Comment by Miloet** [comment]
I found the issue. This setting in the 'BepInEx.cfg' file needs to be set to true:
![image](https://github.com/user-attachments/assets/ada9a825-8d01-4e50-9322-130e1ba1e28d)

Edit: I found a solution that does not require external input from the user. The mod now works without dependency from StaticNetcodeLib. ^^
