### ISSUE TITLE
(CruiserTunes) Playback Order Question

### ISSUE THREAD

**Issue by kayky21** [Miloet/TheManyModsOfLethalCompany#15]
how does the mod sort the songs
like, the order which they'll be played

**Comment by Miloet** [comment]
They are sorted in a bit of a weird way... 
It sorted from lowest to highest Ascii sum- basically you can use this [tool](https://opendsa-server.cs.vt.edu/embed/StringSimple) to find the ascii sum of any text. An easy way to sort them in the order you want them to play is to name them 1, 2, 3, 4, etc. granted that only works till 19 (look at the tool for reference)

**Comment by kayky21** [comment]
dear god
