### ISSUE TITLE
Changing folder location to share music with 'Custom Boombox Music' mod?

### ISSUE THREAD

**Issue by MattWojo73** [Miloet/TheManyModsOfLethalCompany#16]
I noticed the music folder name was almost the same as the 'Custom Boombox Music', except their folder is located directly in BepInEx and has a space between 'Custom' and 'Songs'. 

Is there any easy way I can change the location and folder name dependency to the same as that one so the music could be mutually shared between both mods?

**Comment by Miloet** [comment]
The CrusierTunes folder can also be located in BepInEx but I am afraid that if I do change it or just add it to be both with and without a space it would make it so that some people now have the music from their boombox in CrusierTunes.

I think I have a solution tho. Will implement soon.

**Comment by Miloet** [comment]
If you now rename the folder to "Custom Songs" it should work as long as there isn't a "CustomSongs" folder in bepinex too. hope this helps

**Comment by MattWojo73** [comment]
Thank you for looking into this, but the 'Custom Boombox Music' "Custom Songs" folder is in the folder before plugins (\steamapps\common\Lethal Company\BepInEx)

But going off what you said about how updating the folder name would disrupt pre-existing installs to not find the original folder, I'd imagine changing the location entirely would make it ever more of a problem. 

Is there anyway to configure it so when the mod runs it scans both inside the 'plugins' folder for the "CustomSongs" folder and inside the 'BepInEx' folder for the "Custom Songs" folder and add any found songs to the game?

**Comment by Miloet** [comment]
oh yes, i did add that. it now checks the bepinex folder too

**Comment by MattWojo73** [comment]
Sorry, I realize I keep giving you the run around with this, but at first it wasn't working then I realized it was because the boombox 'Custom Songs' folder has another folder inside it called 'Boombox Music' where it requires the music to be in. 

I think if you changed it to check SteamLibrary\steamapps\common\Lethal Company\BepInEx\Custom Songs\Boombox Music (or to read folders within that "Custom Songs" folder in general) then it will find it. 

I appreciate your efforts thus far, and apologize again for making that mistake.
