### ISSUE TITLE
(CruiserTunes) (Suggestion) OGG Support

### ISSUE THREAD

**Issue by nikkidarkmatter** [Miloet/TheManyModsOfLethalCompany#17]
Would it be possible to add support for the OGG file extension in order to allow for a more compressed file format? Lethal Company loads most files into memory so large audio files could be an issue depending on how this is coded, OGG support would help reduce potential performance impact.

**Comment by Miloet** [comment]
Yeah sorry for the late reply. I havent felt the motivation to do much with Lethal Modding as of late. But I did decide to do a few small fixes so now .ogg is compatible with it.
