### ISSUE TITLE
Incompatibility with Lethal Audio

### ISSUE THREAD

**Issue by DarkerBrightness** [Miloet/TheManyModsOfLethalCompany#2]
I love your plushie mod, unfortunately, it conflicts with Lethal_Audio by Milky224. Uncertain why, since Monster_Plushies sound works like normal. I would appreciate it if there's an easy fix, but else keep up the good work!

**Comment by Miloet** [comment]
Hi, thank you for the rapport. I’ll look into it.

Edit: I was able to replicate the issue and ill look for a solution

**Comment by Miloet** [comment]
I was able to fix it. The issue was the sound files having the same name as some default files, thus being replaced.

**Comment by DarkerBrightness** [comment]
Very nice, thank you!
