### ISSUE TITLE
Lightning Rod desync

### ISSUE THREAD

**Issue by Seviper** [Miloet/TheManyModsOfLethalCompany#3]
Tried out your [lightning rod mod ](https://thunderstore.io/c/lethal-company/p/Mellowdy/LightningRod/) and while it works perfectly when you are the host, my friends still are susceptible to lightning while carrying scrap. I've attached both the logs from my side and from my friend's side.

[LogOutput - Client.log](https://github.com/Miloet/TheManyModsOfLethalCompany/files/15287662/LogOutput.-.Client.log)
[LogOutput - Host.log](https://github.com/Miloet/TheManyModsOfLethalCompany/files/15287663/LogOutput.-.Host.log)

For context, I set the price of the lightning rod to 1, and have the config set to where both "Avert Random" and "Avert Targeted" are at 100000 to make sure that lightning never strikes. I as the host never get hit by lightning, and when my friends are carrying scrap, I never see them get hit by lightning either. But the clients see me getting struck by lightning on their side, and when lightning strikes them on their side, they die (as if the lightning rod isn't on).

The reason for this is that I want to set it to a way higher price in my modpack but to guarantee lightning never hits a player when it is on. So I'd love to see if it's possible to achieve that for both host and players.

**Comment by Miloet** [comment]
I see! 
I think the problem is that the settings are only client sided meaning they require the same settings as you to avoid desync. I will look into it and find a solution.
Edit: that was infact not the case, the settings are synced, will continue looking into it

**Comment by Miloet** [comment]
I pushed an update, I am not 100% sure if it will work flawlessly in cases other than yours but it only failed once striking correctly for me which I am pretty sure was because I didn't turn on the machine in time

**Comment by Lunxara** [comment]
> I pushed an update, I am not 100% sure if it will work flawlessly in cases other than yours but it only failed once striking correctly for me which I am pretty sure was because I didn't turn on the machine in time

So I was happy to see you updated the mod but noticed it still requires Runtime Netcode Patcher which has been deprecated, I hope to see you hopefully remove that dependency soon ^^

**Comment by Miloet** [comment]
I have not yet found another solution to that unfortunatly :(
But on the bright side i believe that the creator deprecated it because
they wont be updating it anymore rather than it not working or such.

**Comment by Seviper** [comment]
Apologies, that was a misclick. Just wanted to comment my update on the desync. The good news is that replicating the situation with just the mod by itself has fixed the desync! The less good news is that once I put it into my modpack, the desync reappeared, aha. I'll be doing more testing this week to see if I can pin down what may be causing some conflicts. Thanks for the swift fix today!

**Comment by Miloet** [comment]
Once you find which mod, or mods, that cause the bug ill attempt to replacate and fix it

**Comment by Seviper** [comment]
Howdy! Sorry for such a long reply time.

LC modding has the same logic that makes car engines work when you sit down to actually try fixing something... the mod mysteriously works now within the same modpack from before. I'm cautiously optimistic with stating the desync issue may be okay for now. If a new one pops up, I'll be sure to send you the logs and try testing it again. There is a different issue I've noticed while using the mod however, so I'll open up a different post for it. Thank you for your patience!
