### ISSUE TITLE
[Suggestion] Add sounds and actual lightning rod on top of ship

### ISSUE THREAD

**Issue by Test-Account666** [Miloet/TheManyModsOfLethalCompany#4]
Hello!

I like the idea of the mod :)

I'd like to suggest adding sounds to the button and the antenna moving.

Also... Maybe also add an actual lightning rod on top of the ship that retracts/extends depending on if the rod is enabled?

That would add to the feel, since a tiny machine doesn't feel like it should have the power to attract lightning reliably

**Comment by Miloet** [comment]
Very good ideas! I am not entirely sure how external changes can be added
but I can look into it. Sounds should be very easy to add however!
