### ISSUE TITLE
[Question] Ozone-Runtime_Netcode_Patcher

### ISSUE THREAD

**Issue by JohnMetroid** [Miloet/TheManyModsOfLethalCompany#5]
Hey there,

Are there expected issues when using Ozone-Runtime_Netcode_Patcher in conjunction with LethalEnergy?  The Netcode patcher is currently listed as "Deprecated" and isn't used for any other mods any more, from what I can see.

Thanks.

**Comment by Miloet** [comment]
Hi!
I asked around on the discord and they said that it was mostly cuz he ended
support for it / there were better methods. I won’t change it for existing
mods unless a new LC update breaks it.

The only negative effect would be slightly more startup for the game and
slightly more memory usage. Given how small scale my mod is it shouldnt be
noticable.

Thanks for reaching out about your concern!
