### ISSUE TITLE
Lightning Rod - Post-Landing Error

### ISSUE THREAD

**Issue by Seviper** [Miloet/TheManyModsOfLethalCompany#6]
Howdy! 

While testing the desync issues out with another person, I found a unique issue that should hopefully be easy to replicate. Using only 
- LightningRod
  - config set to 1000 for both Random and Targeted
- MoreMoneyStart

1. Go to March (which starts as Stormy in Vanilla)
2. Wait until the ship lands on planet
3. Purchase the lightning rod
4. Turn on the lightning rod

The issue I encountered was a massive amount of log spam for the host following these steps. The lighting also seemed to visually disappear as well for both the host and client. I've included the specific error being spammed, but the host log will be attached as well. Both host and client shared a profile code, so all profile info is shared. 

If you need anymore info from me, I'll be happy to assist when time permits.

```
[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
LC_LightningRod.LightningRod.GetRandom (System.Boolean type) (at <bc18b2b127924257ba84a07842e29d36>:IL_0001)
LC_LightningRod.LightningPatch.OverrideLightningStirke (UnityEngine.Vector3& strikePosition, System.Boolean& useTargetedObject, StormyWeather __instance) (at <bc18b2b127924257ba84a07842e29d36>:IL_0034)
(wrapper dynamic-method) StormyWeather.DMD<StormyWeather::LightningStrike>(StormyWeather,UnityEngine.Vector3,bool)
StormyWeather.LightningStrikeRandom () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_00DB)
StormyWeather.Update () (at <255c0877f9414c3aa6f1fe5079ac13f3>:IL_0020)
```
[LogOutput.log](https://github.com/Miloet/TheManyModsOfLethalCompany/files/15410203/LogOutput.log)

**Comment by Miloet** [comment]
Hi!

Thank you for the info! I am unsure of what would cause it but knowing
which function messed it up narrows the search a lot! Ill try having it
fixed within 24 hours

**Comment by Miloet** [comment]
I found the issue btw, very easy fix. Update should be out in about an hour
