### ISSUE TITLE
CruiserTunes - Missing dependency

### ISSUE THREAD

**Issue by Cuzziwuzzi** [Miloet/TheManyModsOfLethalCompany#8]
Installed through r2m with no other mods active. Console shows error; "_Could not load [CruiserTunes 1.0.0] because it has missing dependencies: NicholaScott.BepInEx.RuntimeNetcodeRPCValidator (v0.2.5 or newer)_"

BepInEx config if it's of any help
[BepInExConfig.txt](https://github.com/user-attachments/files/16138455/BepInExConfig.txt)

**Comment by Miloet** [comment]
Thank you for bringing it to my attention. I accidentally forgot to remove some leftovers that weren't used that caused this. It has now been resolved 👍
