### ISSUE TITLE
CruiserTunes - External Loading

### ISSUE THREAD

**Issue by HallowSL** [Miloet/TheManyModsOfLethalCompany#9]
I would like to make a pack for some friends without the need to make them manually add the files themselves, Would It be possible to make it so one could upload a mod with just the CustomSongs folder w/ mp3s inside and still load them, like how MoreCompanyCosmetics works with cosmetics. I did a test for this and it just looks for the CruiserTunes specific path.

**Comment by Miloet** [comment]
i think i could do that. Currently, you can share it with the songs by having the modpack be a zip file but I understand that might not be preferable. The solution I am thinking of is that the mod checks all other folders in the plugins folder for your profile looking for a CustomSongs folder. After that, it loads those songs. To then make a song mod you would just have a CustomSongs folder with the mp3's in it.

Edit: I have now implemented it. Download and check out this mod to see how you can make your own https://thunderstore.io/c/lethal-company/p/Mellowdy/CruiserTunesExampleAddon/
